### ISSUE TITLE
Re-italicize "or"?

### ISSUE THREAD

**Issue by tuskpot** [standardebooks/pedro-carolino_jose-da-fonseca_english-as-she-is-spoke#3]
In the "On a Man" section, there are two entries that have two parts. In the original source, the "or" between these is italicized. It looks like these italics were removed during transcription.

For example:
* The paint _or_ disguise
* Some sirup _or_ sirop

Here's a [link to the source](https://www.google.com/books/edition/English_as_She_is_Spoke/TZFZ95l2QtEC?gbpv=1&bsq=disguise).

I think these italics serve a sensible purpose (to separate the two parts of the definition), so I would be inclined to restore them to match the page scans.

What do you think? Would you want to restore these italics? If so, are there any semantics that are appropriate for this situation?

If you want them, I can add them to the larger pull request that I'm currently working on.

**Comment by acabal** [comment]
Sure, you can put them back in the big pull request. Thanks!
